sonar.projectKey=task12-nodeapi-microservice
sonar.projectName=Task 12 NodeAPI Microservice
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=node_modules/**,coverage/**,dist/**,.git/**,test/**
sonar.sourceEncoding=UTF-8
